version: '3'

services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.develop

  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.develop
    networks:
      - postgres
  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - '8080:8080'
    env_file:
      - .env.develop
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
