services:
  database:
    image: postgres:alpine
    restart: always
    container_name: database
    ports:
      - '5432:5432'
    env_file:
      - .env

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command:
      - npm run start:dev
